# Generated by Django 4.0.3 on 2022-03-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to="api.post"),
            preserve_default=False,
        ),
    ]
